// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"database/sql"
	"time"
)

type Url struct {
	ID          int64          `json:"id"`
	OriginalUrl string         `json:"original_url"`
	ShortCode   string         `json:"short_code"`
	IsCustom    bool           `json:"is_custom"`
	CreatedAt   time.Time      `json:"created_at"`
	ExpiredAt   sql.NullTime   `json:"expired_at"`
	CreatedBy   sql.NullString `json:"created_by"`
}

type User struct {
	ID           int64     `json:"id"`
	UserID       string    `json:"user_id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Email        string    `json:"email"`
	CreatedAt    time.Time `json:"created_at"`
}
