// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) error
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeleteOutdatedURLs(ctx context.Context) error
	GetURLByShortCode(ctx context.Context, shortCode string) (Url, error)
	GetUserInfoFromEmail(ctx context.Context, email string) (User, error)
	GetUserInfoFromUserID(ctx context.Context, userID string) (User, error)
	GetUserInfoFromUsername(ctx context.Context, username string) (User, error)
	GetUserShortURLs(ctx context.Context, arg GetUserShortURLsParams) ([]Url, error)
	IsNewUserAvailable(ctx context.Context, arg IsNewUserAvailableParams) (bool, error)
	IsShortCodeAvailable(ctx context.Context, shortCode string) (bool, error)
	ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
