[db]
driver_name = "pgx"
database_host = "localhost"
database_port = 5432
database_name = "url_db"
username = "user"
password = "pass"
ssl_mode = "disable"
max_idle_conns = 10
max_open_conns = 100

[cacher]
cacher_url = "localhost:6379"
password = ""
db = 0
average_expiration = "1h"

[code_generator]
short_code_length = 7

[service]
frontend_base_url = "http://localhost:3000"
default_expiration = "720h"
outdated_url_cleanup_interval = "2h"

[server]
port = 8080
write_timeout = "10s"
read_timeout = "10s"
graceful_shutdown_timeout = "5s"
