[db]
driver_name = "pgx"
database_host = "localhost"
database_port = 5432
database_name = "url_db"
username = "user"
password = "pass"
ssl_mode = "disable"
max_idle_conns = 10
max_open_conns = 100

[cacher]
cacher_url = "localhost:6379"
password = ""
db = 0
url_average_expiration = "1h"
email_code_expiration = "5m"

[code_generator]
short_code_length = 7

[password_manager]
current_node_number = 1
password_hash_cost = 12

[auth]
secret_key = "your_secret_key"
jwt_expiration = "24h"

[mailer]
smtp_host = "smtp.example.com"
smtp_port = 587
username = "example_user"
password = "example_pass"
from_mail = "example@example.ocm"

[url_service]
short_link_base_url = "http://localhost:8080"
default_expiration = "720h"
outdated_url_cleanup_interval = "2h"

[server]
port = 8080
write_timeout = "10s"
read_timeout = "10s"
graceful_shutdown_timeout = "5s"
