# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Publish release on tag

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'
          
      - name: Build
        run: |
          env GOOS=linux GOARCH=amd64 go build -o build/shorter_url_linux_amd64
          env GOOS=linux GOARCH=arm64 go build -o build/shorter_url_linux_arm64
          env GOOS=darwin GOARCH=arm64 go build -o build/shorter_url_macos_arm64

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/shorter_url_linux_amd64
            build/shorter_url_linux_arm64
            build/shorter_url_macos_arm64
